### ISSUE TITLE
[Feature request] Allow selecting specific year to generate a whole year's heatmap

### ISSUE THREAD

**Issue by Quorafind** [pengx17/logseq-plugin-heatmap#3]
Like 
![image](https://user-images.githubusercontent.com/13215013/122144101-5cede980-ce85-11eb-8d41-e2ee4204c5de.png)

But the year selector could be moved to the top of the heatmap.

**Comment by pengx17** [comment]
@Quorafind I added a date range helper which allows the user to go forward or backward in 4 months' time step. Since logseq is pretty young and people usually do not take notes earlier than 2 years, I hope this is good enough other than having yearly toggles.
![](https://github.com/pengx17/logseq-plugin-heatmap/raw/master/daterange-selection.gif)

**Comment by Quorafind** [comment]
Nice job. If anyone need, please open the issue again.
